name: Tests

on:
  push:
    branches: [main]
    paths-ignore:
      - "**/*.md"
  pull_request:
    branches: [main]

jobs:
  coverage:
    name: Code Coverage
    uses: ./.github/workflows/reusable.yml
    secrets: inherit
    with:
      coverage: true
    permissions:
      statuses: write

  regress-clickhouse:
    name: ClickHouse regression
    uses: ./.github/workflows/reusable.yml
    secrets: inherit
    with:
      clickhouse-version: ${{ matrix.version }}
    strategy:
      fail-fast: false
      matrix:
        version:
          - "latest"
          - "25.11"
          - "25.10"
          - "25.8"
          - "25.3"

  regress-dotnet:
    name: .NET regression
    uses: ./.github/workflows/reusable.yml
    secrets: inherit
    with:
      framework: ${{ matrix.framework }}
    strategy:
      fail-fast: false
      matrix:
        framework: ["net10.0", "net9.0", "net6.0"]

  integration:
    name: Integration
    uses: ./.github/workflows/tests-integration.yml
    secrets: inherit

  cloud:
    name: Cloud
    uses: ./.github/workflows/tests-cloud.yml
    secrets: inherit

  windows:
    name: Windows
    uses: ./.github/workflows/tests-windows.yml
    secrets: inherit

  macos:
    name: macOS
    uses: ./.github/workflows/tests-macos.yml
    secrets: inherit
